# Generated by Django 6.0.2 on 2026-02-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_status_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_rating',
            field=models.CharField(choices=[('ALL', 'Todo publico'), ('7+', 'Mayores de 7'), ('12+', 'Mayores de 12'), ('15+', 'Mayores de 15'), ('18+', 'Solo adultos')], default='ALL', max_length=8),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
