# Generated by Django 6.0.2 on 2026-02-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_event_review_per_user',
        ),
    ]
