# Generated by Django 6.0.2 on 2026-02-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_review_unique_event_review_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationlog',
            options={'permissions': [('can_validate_tickets', 'Can validate ticket tokens')]},
        ),
    ]
