# Generated by Django 6.0.2 on 2026-02-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationlog',
            options={'permissions': [('can_validate_tickets', 'Puede validar tokens de boletas')]},
        ),
        migrations.AlterField(
            model_name='event',
            name='age_rating',
            field=models.CharField(choices=[('ALL', 'Todo público'), ('7+', 'Mayores de 7'), ('12+', 'Mayores de 12'), ('15+', 'Mayores de 15'), ('18+', 'Solo adultos')], default='ALL', max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Pagada'), ('VOID', 'Anulada')], default='PAID', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('UNUSED', 'No usada'), ('USED', 'Usada'), ('VOID', 'Anulada')], default='UNUSED', max_length=16),
        ),
        migrations.AlterField(
            model_name='validationlog',
            name='outcome',
            field=models.CharField(choices=[('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], max_length=16),
        ),
        migrations.CreateModel(
            name='ReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LIKE', 'Me gusta'), ('DISLIKE', 'No me gusta')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'user'), name='unique_review_reaction_per_user')],
            },
        ),
    ]
