# Generated by Django 6.0.2 on 2026-03-26 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_event_buyer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('general', 'General'), ('vip', 'VIP')], max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('price_usd', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_total', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('number_prefix', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='validationlog',
            options={'permissions': [('can_validate_tickets', 'Can validate ticket tokens')]},
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_raffle_number_per_event',
        ),
        migrations.AlterField(
            model_name='event',
            name='age_rating',
            field=models.CharField(choices=[('ALL', 'Toda la familia'), ('18+', 'Mayores de edad')], default='ALL', max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobacion'), ('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewreaction',
            name='reaction',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'No Like')], max_length=8),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OMITTED', 'Dismissed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('UNUSED', 'Disponible'), ('USED', 'Usada'), ('VOID', 'Anulada')], default='UNUSED', max_length=16),
        ),
        migrations.AlterField(
            model_name='validationlog',
            name='outcome',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=16),
        ),
        migrations.AddField(
            model_name='eventtickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='core.event'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.eventtickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.eventtickettype'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('raffle_number__isnull', False)), fields=('ticket_type', 'raffle_number'), name='unique_raffle_number_per_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='eventtickettype',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='unique_ticket_type_code_per_event'),
        ),
    ]
