# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_productredemption_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MomentBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MomentMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_type", models.CharField(choices=[("IMAGE", "Imagen"), ("VIDEO", "Video")], max_length=16)),
                ("file", models.FileField(upload_to="moments/")),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_items", to="core.momentblock"),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
