# Generated by Django 6.0.2 on 2026-06-04 03:15

from django.db import migrations, models


def seed_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "whatsapp_url": "https://wa.me/16788868874?text=Hola%20%F0%9F%8E%AD%2C%20quiero%20recibir%20informaci%C3%B3n%20sobre%20el%20Carnaval%20de%20Barranquilla%20en%20Atlanta.%20%C2%A1Gracias",
            "instagram_url": "https://www.instagram.com/carnaval.bq.atl/",
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_momentblock_momentmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del sitio',
                'verbose_name_plural': 'Configuracion del sitio',
            },
        ),
        migrations.RunPython(seed_site_settings, noop_reverse),
    ]
