# Generated by Django 6.0.2 on 2026-06-04 03:37

from django.db import migrations, models


def seed_footer_content(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "footer_primary_text": "Una experiencia que une arte, cultura y la alegria del Carnaval de Barranquilla en Atlanta.",
            "footer_tagline": "Vive la experiencia.",
            "footer_copyright_text": "2026 MaruVision. Todos los derechos reservados.",
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_primary_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(seed_footer_content, noop_reverse),
    ]
