# Generated by Django 6.0.2 on 2026-06-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_sitesettings_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status_detail',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de pago'), ('PAID', 'Pagada'), ('FAILED', 'Pago fallido'), ('CANCELED', 'Pago cancelado'), ('REFUNDED', 'Reembolsada'), ('VOID', 'Anulada')], default='PAID', max_length=16),
        ),
    ]
