# Generated by Django 6.0.2 on 2026-06-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_order_payment_confirmed_at_order_payment_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de pago'), ('PAID', 'Pagada'), ('FAILED', 'Pago fallido'), ('CANCELED', 'Pago cancelado'), ('REFUNDED', 'Reembolsada'), ('VOID', 'Anulada')], default='PENDING', max_length=16),
        ),
    ]
