from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path
from django.urls import reverse_lazy

from .views import (
    add_product_to_cart,
    add_ticket_to_cart,
    CustomerLoginView,
    cart_detail,
    checkout_cart,
    clear_cart,
    delete_event_review,
    delete_event_image,
    delete_event,
    download_ticket_qr_jpg,
    delete_user,
    edit_profile,
    EventDetailView,
    EventListView,
    MomentsView,
    grant_validator_role,
    HomeView,
    manage_moments,
    manage_site_settings,
    update_moment_block,
    delete_moment_block,
    create_event,
    create_user,
    block_user_account,
    unblock_user_account,
    my_tickets,
    delete_notification,
    notifications_list,
    notifications_unread_api,
    react_to_review,
    report_review,
    resend_email_verification,
    remove_cart_item,
    rules_page,
    review_reports_list,
    omit_review_report,
    delete_reported_review,
    demote_admin_user,
    promote_user_to_admin,
    purchase_event,
    revoke_validator_role,
    submit_event_review,
    signup,
    start_stripe_checkout,
    stripe_checkout_cancel,
    stripe_checkout_success,
    stripe_webhook,
    update_event,
    update_cart_item,
    add_event_images,
    about_page,
    user_tickets,
    user_tickets_by_user,
    user_ticket_qrs_by_user,
    user_products,
    user_products_by_user,
    user_list,
    validate_ticket_token,
    validate_product_redemption,
    verify_email_confirm,
    email_verification_sent,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("rules/", rules_page, name="rules_page"),
    path("about/", about_page, name="about_page"),
    path("events/", EventListView.as_view(), name="event_list"),
    path("momentos/", MomentsView.as_view(), name="moments_page"),
    path("staff/momentos/", manage_moments, name="manage_moments"),
    path("staff/site-settings/", manage_site_settings, name="manage_site_settings"),
    path("staff/momentos/<int:pk>/editar/", update_moment_block, name="update_moment_block"),
    path("staff/momentos/<int:pk>/delete/", delete_moment_block, name="delete_moment_block"),
    path("cart/", cart_detail, name="cart_detail"),
    path("cart/checkout/", checkout_cart, name="checkout_cart"),
    path("cart/orders/<int:order_id>/stripe-checkout/", start_stripe_checkout, name="start_stripe_checkout"),
    path("payments/stripe/success/", stripe_checkout_success, name="stripe_checkout_success"),
    path("payments/stripe/cancel/", stripe_checkout_cancel, name="stripe_checkout_cancel"),
    path("payments/stripe/webhook/", stripe_webhook, name="stripe_webhook"),
    path("cart/clear/", clear_cart, name="clear_cart"),
    path("cart/items/<int:pk>/update/", update_cart_item, name="update_cart_item"),
    path("cart/items/<int:pk>/remove/", remove_cart_item, name="remove_cart_item"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event_detail"),
    path("events/<int:pk>/buy/", purchase_event, name="purchase_event"),
    path("events/<int:pk>/add-ticket/", add_ticket_to_cart, name="add_ticket_to_cart"),
    path("events/<int:pk>/add-product/", add_product_to_cart, name="add_product_to_cart"),
    path("events/<int:pk>/review/", submit_event_review, name="submit_event_review"),
    path(
        "events/<int:event_pk>/reviews/<int:review_pk>/react/<str:reaction>/",
        react_to_review,
        name="react_to_review",
    ),
    path(
        "events/<int:event_pk>/reviews/<int:review_pk>/report/",
        report_review,
        name="report_review",
    ),
    path(
        "staff/events/<int:event_pk>/reviews/<int:review_pk>/delete/",
        delete_event_review,
        name="delete_event_review",
    ),
    path("staff/events/<int:pk>/update/", update_event, name="update_event"),
    path("staff/events/<int:pk>/delete/", delete_event, name="delete_event"),
    path("staff/events/<int:pk>/images/upload/", add_event_images, name="add_event_images"),
    path(
        "staff/events/<int:event_pk>/images/<int:image_pk>/delete/",
        delete_event_image,
        name="delete_event_image",
    ),
    path("my-tickets/", my_tickets, name="my_tickets"),
    path(
        "my-tickets/<int:ticket_id>/download-qr-jpg/",
        download_ticket_qr_jpg,
        name="download_ticket_qr_jpg",
    ),
    path("accounts/notifications/", notifications_list, name="notifications_list"),
    path(
        "accounts/notifications/<int:pk>/delete/",
        delete_notification,
        name="delete_notification",
    ),
    path(
        "accounts/notifications/unread/",
        notifications_unread_api,
        name="notifications_unread_api",
    ),
    path("staff/events/create/", create_event, name="create_event"),
    path("staff/reports/", review_reports_list, name="review_reports_list"),
    path("staff/reports/<int:pk>/omit/", omit_review_report, name="omit_review_report"),
    path(
        "staff/reports/<int:pk>/delete-review/",
        delete_reported_review,
        name="delete_reported_review",
    ),
    path("staff/users/", user_list, name="user_list"),
    path("staff/users/create/", create_user, name="create_user"),
    path("staff/users/<int:pk>/delete/", delete_user, name="delete_user"),
    path("staff/users/<int:pk>/promote/", promote_user_to_admin, name="promote_user_to_admin"),
    path("staff/users/<int:pk>/demote/", demote_admin_user, name="demote_admin_user"),
    path("staff/users/<int:pk>/grant-validator/", grant_validator_role, name="grant_validator_role"),
    path("staff/users/<int:pk>/revoke-validator/", revoke_validator_role, name="revoke_validator_role"),
    path("staff/users/<int:pk>/block/", block_user_account, name="block_user_account"),
    path("staff/users/<int:pk>/unblock/", unblock_user_account, name="unblock_user_account"),
    path("staff/users/<int:user_id>/tickets/", user_tickets_by_user, name="user_tickets_by_user"),
    path("staff/users/<int:user_id>/products/", user_products_by_user, name="user_products_by_user"),
    path("staff/users/<int:user_id>/ticket-qrs/", user_ticket_qrs_by_user, name="user_ticket_qrs_by_user"),
    path("staff/products/", user_products, name="user_products"),
    path("staff/tickets/", user_tickets, name="user_tickets"),
    path("staff/validate-token/", validate_ticket_token, name="validate_token"),
    path("staff/validate-products/", validate_product_redemption, name="validate_product_redemption"),
    path("accounts/signup/", signup, name="signup"),
    path("accounts/verify-email/sent/", email_verification_sent, name="email_verification_sent"),
    path("accounts/verify-email/confirm/", verify_email_confirm, name="verify_email_confirm"),
    path("accounts/verify-email/resend/", resend_email_verification, name="resend_email_verification"),
    path("accounts/profile/", edit_profile, name="edit_profile"),
    path("accounts/login/", CustomerLoginView.as_view(), name="login"),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            email_template_name="registration/password_reset_email.txt",
            html_email_template_name="registration/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            success_url=reverse_lazy("password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]
