from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    CustomerLoginView,
    delete_event_review,
    delete_event_image,
    download_ticket_qr_jpg,
    delete_user,
    edit_profile,
    EventDetailView,
    EventListView,
    grant_validator_role,
    HomeView,
    create_event,
    create_user,
    block_user_account,
    unblock_user_account,
    my_tickets,
    delete_notification,
    notifications_list,
    notifications_unread_api,
    react_to_review,
    report_review,
    edit_rules,
    rules_page,
    review_reports_list,
    omit_review_report,
    delete_reported_review,
    demote_admin_user,
    promote_user_to_admin,
    purchase_event,
    revoke_validator_role,
    submit_event_review,
    signup,
    update_event,
    add_event_images,
    about_page,
    user_tickets,
    user_tickets_by_user,
    user_ticket_qrs_by_user,
    user_list,
    validate_ticket_token,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("rules/", rules_page, name="rules_page"),
    path("about/", about_page, name="about_page"),
    path("events/", EventListView.as_view(), name="event_list"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event_detail"),
    path("events/<int:pk>/buy/", purchase_event, name="purchase_event"),
    path("events/<int:pk>/review/", submit_event_review, name="submit_event_review"),
    path(
        "events/<int:event_pk>/reviews/<int:review_pk>/react/<str:reaction>/",
        react_to_review,
        name="react_to_review",
    ),
    path(
        "events/<int:event_pk>/reviews/<int:review_pk>/report/",
        report_review,
        name="report_review",
    ),
    path(
        "staff/events/<int:event_pk>/reviews/<int:review_pk>/delete/",
        delete_event_review,
        name="delete_event_review",
    ),
    path("staff/events/<int:pk>/update/", update_event, name="update_event"),
    path("staff/events/<int:pk>/images/upload/", add_event_images, name="add_event_images"),
    path(
        "staff/events/<int:event_pk>/images/<int:image_pk>/delete/",
        delete_event_image,
        name="delete_event_image",
    ),
    path("my-tickets/", my_tickets, name="my_tickets"),
    path(
        "my-tickets/<int:ticket_id>/download-qr-jpg/",
        download_ticket_qr_jpg,
        name="download_ticket_qr_jpg",
    ),
    path("accounts/notifications/", notifications_list, name="notifications_list"),
    path(
        "accounts/notifications/<int:pk>/delete/",
        delete_notification,
        name="delete_notification",
    ),
    path(
        "accounts/notifications/unread/",
        notifications_unread_api,
        name="notifications_unread_api",
    ),
    path("staff/events/create/", create_event, name="create_event"),
    path("staff/rules/edit/", edit_rules, name="edit_rules"),
    path("staff/reports/", review_reports_list, name="review_reports_list"),
    path("staff/reports/<int:pk>/omit/", omit_review_report, name="omit_review_report"),
    path(
        "staff/reports/<int:pk>/delete-review/",
        delete_reported_review,
        name="delete_reported_review",
    ),
    path("staff/users/", user_list, name="user_list"),
    path("staff/users/create/", create_user, name="create_user"),
    path("staff/users/<int:pk>/delete/", delete_user, name="delete_user"),
    path("staff/users/<int:pk>/promote/", promote_user_to_admin, name="promote_user_to_admin"),
    path("staff/users/<int:pk>/demote/", demote_admin_user, name="demote_admin_user"),
    path("staff/users/<int:pk>/grant-validator/", grant_validator_role, name="grant_validator_role"),
    path("staff/users/<int:pk>/revoke-validator/", revoke_validator_role, name="revoke_validator_role"),
    path("staff/users/<int:pk>/block/", block_user_account, name="block_user_account"),
    path("staff/users/<int:pk>/unblock/", unblock_user_account, name="unblock_user_account"),
    path("staff/users/<int:user_id>/tickets/", user_tickets_by_user, name="user_tickets_by_user"),
    path("staff/users/<int:user_id>/ticket-qrs/", user_ticket_qrs_by_user, name="user_ticket_qrs_by_user"),
    path("staff/tickets/", user_tickets, name="user_tickets"),
    path("staff/validate-token/", validate_ticket_token, name="validate_token"),
    path("accounts/signup/", signup, name="signup"),
    path("accounts/profile/", edit_profile, name="edit_profile"),
    path("accounts/login/", CustomerLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]
